---
- name: Check if reboot required
  ansible.builtin.command: needs-restarting -r
  register: reboot_required_cmd
  failed_when: false
  changed_when: false

- name: Schedule reboot
  ansible.builtin.command: /bin/true
  notify: Reboot server
  when: reboot_required_cmd.rc == 1
  changed_when: reboot_required_cmd.rc == 1
